In [31]:
import random
import numpy as np
import pandas as pd
from pandas import read_csv
import seaborn as sns
from sklearn.cross_validation import train_test_split
from sklearn.ensemble.forest import ExtraTreesClassifier
from sklearn import metrics
from sklearn import preprocessing

authorship = read_csv('../data/authorship.csv')
authorship.head(2)

a  all  also  an  and  any  are  as  at  be   ...    what  when  which  \
0  46   12     0   3   66    9    4  16  13  13   ...       7     5      6   
1  35   10     0   7   44    4    3  18  16   9   ...       5     7      7   

   who  will  with  would  your  BookID  Author  
0    8     4     9      1     0       1  Austen  
1    3     5    14      8     0       1  Austen  

[2 rows x 71 columns]

In [32]:
authors = list(set(authorship.Author.values))
print authors

['Austen', 'London', 'Shakespeare', 'Milton']


In [33]:
le = preprocessing.LabelEncoder()
le.fit(authors)
authorship['Author_num'] = le.transform(authorship['Author'])
print authorship['Author_num'].head(2)

0    0
1    0
Name: Author_num, dtype: int64


In [65]:
# Create a random variable (random forests work best with a random variable)
authorship['random'] = [random.random() for i in range(841)]

In [34]:
#What are some of the stop words we're looking at?
features = list(authorship.columns)
features.remove('Author')
features.remove('Author_num')
features.remove('BookID')
print features

['a', 'all', 'also', 'an', 'and', 'any', 'are', 'as', 'at', 'be', 'been', 'but', 'by', 'can', 'do', 'down', 'even', 'every', 'for', 'from', 'had', 'has', 'have', 'her', 'his', 'if', 'in', 'into', 'is', 'it', 'its', 'may', 'more', 'must', 'my', 'no', 'not', 'now', 'of', 'on', 'one', 'only', 'or', 'our', 'should', 'so', 'some', 'such', 'than', 'that', 'the', 'their', 'then', 'there', 'things', 'this', 'to', 'up', 'upon', 'was', 'were', 'what', 'when', 'which', 'who', 'will', 'with', 'would', 'your']


In [67]:
# create a test and training set
all_scores=[]
for nestimator in range(20,55,5):
    for tsize in [x / 10.0 for x in range(1, 5)]:
        x_train, x_test, y_train, y_test = train_test_split(authorship[features], authorship.Author_num.values, test_size=0.5, random_state=123)
        x, y = authorship[features], authorship.Author_num.values
        # Fit Model
        from sklearn.cross_validation import cross_val_score

        etclf = ExtraTreesClassifier(n_estimators=nestimator)
        etclf.fit(x_train, y_train)

        scores = cross_val_score(etclf, x, y)
        all_scores.extend(scores)
        print "=============no of estimators = ", nestimator, " test_size = ",tsize
        print scores.mean()

        # Print Confusion Matrix
        print metrics.confusion_matrix(etclf.predict(x_test), y_test)
        print authors

print all_scores


=============no of estimators =  20  test_size =  0.1
0.976244854045
[[168   4   0   1]
 [  2 130   0   1]
 [  0   0  23   0]
 [  0   0   2  90]]
['Austen', 'London', 'Shakespeare', 'Milton']
=============no of estimators =  20  test_size =  0.2
0.975088241665
[[168   0   0   1]
 [  1 133   1   1]
 [  0   0  24   0]
 [  1   1   0  90]]
['Austen', 'London', 'Shakespeare', 'Milton']
=============no of estimators =  20  test_size =  0.3
0.981040835538
[[168   4   0   0]
 [  2 130   0   1]
 [  0   0  25   0]
 [  0   0   0  91]]
['Austen', 'London', 'Shakespeare', 'Milton']
=============no of estimators =  20  test_size =  0.4
0.973863780181
[[170   2   0   1]
 [  0 131   1   2]
 [  0   0  24   0]
 [  0   1   0  89]]
['Austen', 'London', 'Shakespeare', 'Milton']
=============no of estimators =  25  test_size =  0.1
0.977465109006
[[169   0   0   1]
 [  1 133   3   1]
 [  0   0  22   0]
 [  0   1   0  90]]
['Austen', 'London', 'Shakespeare', 'Milton']
=============no of estimators =  25  tes

In [58]:
ndf = pd.DataFrame(all_scores)

In [68]:
ndf.describe()

0
count  84.000000
mean    0.977811
std     0.015540
min     0.932624
25%     0.970669
50%     0.982206
75%     0.989209
max     0.996403

In [42]:
import random
import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt
from pylab import *
import numpy as np
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import auc
from sklearn import metrics
from numpy import random

# Matplotlib Styles
mplc = {'axes.labelsize': 17,
'axes.titlesize': 16,
'figure.figsize': [18, 8],
'grid.linewidth': 1.6,
'legend.fontsize': 17,
'lines.linewidth': 2,
'lines.markeredgewidth': 0.0,
'lines.markersize': 11,
'patch.linewidth': 0.5,
'xtick.labelsize': 16,
'xtick.major.pad': 20,
'xtick.major.width': 2,
'xtick.minor.width': 1,
'ytick.labelsize': 16.0,
'ytick.major.pad': 20,
'ytick.major.width': 2,
'ytick.minor.width': 1 }


import numpy as np
import matplotlib.pyplot as plt

from sklearn import clone
from sklearn.datasets import load_iris
from sklearn.ensemble import (RandomForestClassifier, ExtraTreesClassifier,
                              AdaBoostClassifier)
from sklearn.externals.six.moves import xrange
from sklearn.tree import DecisionTreeClassifier

# Parameters
n_classes = 69
n_estimators = 30
plot_colors = "ryb"
cmap = plt.cm.RdYlBu
plot_step = 0.02  # fine step width for decision surface contours
plot_step_coarser = 0.5  # step widths for coarse classifier guesses
RANDOM_SEED = 13  # fix the seed on each iteration

# Load data
#iris = load_iris()                      
#

plot_idx = 1

models = [DecisionTreeClassifier(max_depth=None),
          RandomForestClassifier(n_estimators=n_estimators),
          ExtraTreesClassifier(n_estimators=n_estimators),
          AdaBoostClassifier(DecisionTreeClassifier(max_depth=3),
                             n_estimators=n_estimators)]

authorship = read_csv('../data/authorship.csv')
authors = list(set(authorship.Author.values))
le = preprocessing.LabelEncoder()
le.fit(authors)
authorship['Author_num'] = le.transform(authorship['Author'])
#authorship.drop(['BookID','Author'],1,inplace=True)
features = list(authorship.columns)
features.remove('Author')
features.remove('Author_num')
features.remove('BookID')

import time

with sns.plotting_context("talk", font_scale=1, rc=mplc):


#    for pair in ([0, 1], [0, 2], [2, 3]):
        for model in models:
            # We only take the two corresponding features
#            X = iris.data[:, pair]
#            y = iris.target

            X = np.array(authorship[features])
            y = np.array(authorship.Author_num.values)

#            print type(X), X.shape
#            print type(y), y.shape

            # Shuffle
            idx = np.arange(X.shape[0])
            np.random.seed(RANDOM_SEED)
            np.random.shuffle(idx)
            X = X[idx]
            y = y[idx]

#            print type(X), X.shape
#            print type(y), y.shape
            
            # Standardize
            mean = X.mean(axis=0)
            std = X.std(axis=0)
            X = (X - mean) / std

            # Train
            clf = clone(model)
            start = time.clock()
            clf = model.fit(X, y)
            end = time.clock()

            scores = clf.score(X, y)
            # Create a title for each column and the console by using str() and
            # slicing away useless parts of the string
            model_title = str(type(model)).split(".")[-1][:-2][:-len("Classifier")]
            model_details = model_title
            if hasattr(model, "estimators_"):
                model_details += " with {} estimators".format(len(model.estimators_))
            print( model_details + "has a score of", scores, " in " + str(end-start) + "s"  )

#
# CAN'T FIGURE OUT THE PLOTTING
#

#            plt.subplot(3, 4, plot_idx)
#            if plot_idx <= len(models):
                # Add a title at the top of each column
#                plt.title(model_title)

            # Now plot the decision boundary using a fine mesh as input to a
            # filled contour plot
#            x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
#            y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
#            xx, yy = np.meshgrid(np.arange(x_min, x_max, plot_step),
#                                 np.arange(y_min, y_max, plot_step))
#            print "x_min = ", x_min
#            print "x_max = ", x_max
#            print "y_min = ", y_min
#            print "y_max = ", y_max
#            print "xx = ", xx
#            print "yy = ", yy
#            print "len(xx.ravel) = ", len(xx.ravel())
#            print "len(yy.ravel) = ", len(yy.ravel())
#            print "len(np.c_[xx.ravel(), yy.ravel()]) = ", len(np.c_[xx.ravel(), yy.ravel()])
            
            # Plot either a single DecisionTreeClassifier or alpha blend the
            # decision surfaces of the ensemble of classifiers
#            if isinstance(model, DecisionTreeClassifier):
#                Z = model.predict(np.c_[xx.ravel(), yy.ravel()])
#                Z = Z.reshape(xx.shape)
#                cs = plt.contourf(xx, yy, Z, cmap=cmap)
#            else:
                # Choose alpha blend level with respect to the number of estimators
                # that are in use (noting that AdaBoost can use fewer estimators
                # than its maximum if it achieves a good enough fit early on)
#                estimator_alpha = 1.0 / len(model.estimators_)
#                for tree in model.estimators_:
#                    Z = tree.predict(np.c_[xx.ravel(), yy.ravel()])
#                    Z = Z.reshape(xx.shape)
#                    cs = plt.contourf(xx, yy, Z, alpha=estimator_alpha, cmap=cmap)

            # Build a coarser grid to plot a set of ensemble classifications
            # to show how these are different to what we see in the decision
            # surfaces. These points are regularly space and do not have a black outline
#            xx_coarser, yy_coarser = np.meshgrid(np.arange(x_min, x_max, plot_step_coarser),
#                                                 np.arange(y_min, y_max, plot_step_coarser))
#            Z_points_coarser = model.predict(np.c_[xx_coarser.ravel(), yy_coarser.ravel()]).reshape(xx_coarser.shape)
#            cs_points = plt.scatter(xx_coarser, yy_coarser, s=15, c=Z_points_coarser, cmap=cmap, edgecolors="none")

            # Plot the training points, these are clustered together and have a
            # black outline
##            for i, c in zip(xrange(n_classes), plot_colors):
#                idx = np.where(y == i)
#                plt.scatter(X[idx, 0], X[idx, 1], c=c, label=iris.target_names[i],
#                            cmap=cmap)

#            plot_idx += 1  # move on to the next plot in sequence

#        plt.suptitle("Classifiers on feature subsets of the Iris dataset")
#        plt.axis("tight")

#        plt.show()

('DecisionTreehas a score of', 1.0, ' in 0.015556s')
('RandomForest with 30 estimatorshas a score of', 1.0, ' in 0.071715s')
('ExtraTrees with 30 estimatorshas a score of', 1.0, ' in 0.048867s')
('AdaBoost with 30 estimatorshas a score of', 1.0, ' in 0.21631s')
